version : '3'

services:
  api:
    depends_on:
      - db
    image: strapi/strapi
    restart: unless-stopped
    container_name: arms2backend
    environment:
      NODE_ENV: production
      APP_NAME: strapi-app
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi-dev
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: "false"
    ports: 
      - 1338:1338
    volumes:
      - ./app:/srv/app
    command: 'strapi start'
  db:
    container_name: str_mysql
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi-dev
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: Arms@v2y2020
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '3307:3306'
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '19090:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Arms@v2y2020
